#
###################################
# Site wide configuration
####################################
#
title: LuizSD
email: lsantosdutra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple and awesome blog theme powered by jekyll. Inspired by PureCSS blog layout and build by bootstrap 4.
url: http://www.luizsd.com # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter: pygments
excerpt_separator: <!--more-->
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

#
###################################
# Jekyll configuration
####################################
#
owner:
  name: Luiz Santos
  avatar: bio-photo.jpg
  bio: "Um Dev a mais no mundo."
  email: lsantosdutra@gmail.com
  disqus-shortname: LuizSD
  twitter: luizsd 
  facebook: luizsd
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: luizsd
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: LuizSD
  xing: #username
  instagram: luizsd
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
